Repository gofrs/flock, pull requests merged in 2024-06, with the labels that each got.

#57 chore: add go modules
  go.mod
  go.sum
Labels: enhancement

#66 docs: remove reference to sync.Locker
  README.md
Labels: bug, documentation

#67 chore(ci): remove Syscall6 deprecation exclusion
  .golangci.yml
Labels: enhancement, infrastructure

#68 chore(ci): add scorecard workflow
  .github/workflows/scorecards.yml
Labels: enhancement, infrastructure

#69 chore: add security policies
  SECURITY.md
Labels: enhancement, documentation, infrastructure

#70 chore: migrate from gopkg.in/check to stretchr/testify
  flock_test.go
  go.mod
  go.sum
Labels: enhancement, infrastructure

#72 chore(ci): group dependabot PRs
  .github/dependabot.yml
Labels: enhancement, infrastructure

#71 docs: improve security policies
  SECURITY.md
Labels: enhancement, documentation

#74 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, infrastructure

#75 chore: improve linter configuration
  .github/workflows/linting.yml
  .golangci.yml
  flock.go
  flock_aix.go
  flock_example_test.go
  flock_test.go
  flock_unix.go
  flock_winapi.go
  flock_windows.go
Labels: enhancement, infrastructure

#63 feat: add support for Illumos/Solaris
  build.sh
  flock.go
  flock_test.go
  flock_unix.go
  flock_unix_variants.go
Labels: enhancement

#76 feat: add option to define flag and permissions of the file
  flock.go
Labels: enhancement

#77 tests: remove files generated during tests
  flock.go
  flock_internal_test.go
  flock_test.go
  flock_windows.go
Labels: bug

#78 feat: use options on retry (unix)
  flock.go
  flock_unix.go
  flock_unix_variants.go
  flock_windows.go
Labels: enhancement
