Repository gofrs/flock, pull requests merged in 2024-07, with the labels that each got.

#80 feat: differentation of solaris and illumos
  flock_unix.go
  flock_unix_variants.go
Labels: enhancement

#83 chore: replace os.(FileMode,PathError) by fs.(...)
  flock.go
  flock_unix_fcntl.go
Labels: enhancement

#84 fix: update fnctl implementation
  flock_unix_fcntl.go
Labels: bug, os/aix, os/solaris

#85 feat: use runtime errors instead of compilation errors for unusupported platforms
  build.sh
  flock_example_test.go
  flock_internal_test.go
  flock_others.go
  flock_test.go
  flock_unix.go
  flock_windows.go
Labels: enhancement, os/plan9, os/js, os/wasip1

#87 refactor: use x/sys/* instead of Syscall when possible
  flock_unix.go
  flock_unix_fcntl.go
  flock_windows.go
Labels: enhancement

#89 tests: add tests about directory support
  flock_internal_test.go
  flock_test.go
Labels: enhancement

#91 chore: factorize
  flock.go
  flock_unix.go
Labels: enhancement

#95 fix: missing read-write flag in reopenFDOnError
  flock.go
  flock_unix.go
  flock_unix_fcntl.go
  flock_windows.go
Labels: bug
